version: '3'

services:
  gos-api:
    container_name: p2p_gate
    image: p2p_nest:latest
    environment:
      - HOST=http://localhost:7000
      - PORT=7000
      - RECEIVER_CARD='4790043142218391'
      - PAY_URL='https://www.tinkoff.ru/api/common/v1/pay?appName=paymentsc2c&appVersion=2.9.6&origin=web%2Cib5%2Cplatform&wuid=c67b57b2a6e9c1507438f222aa30c45&sessionid=qGaC1UOxjUWfN4G5P2JLhYoRKHrCkZxy.ds-prod-api'
      - CONFIRM_URL='https://www.tinkoff.ru/api/common/v1/confirm?appName=paymentsc2c&appVersion=2.9.6&origin=web%2Cib5%2Cplatform&sessionid=qGaC1UOxjUWfN4G5P2JLhYoRKHrCkZxy.ds-prod-api62&wuid=c67b57b2a6e9c1507438f222aa30c45e&confirmationType=3DSecure'
      - COMMISSION_URL='https://www.tinkoff.ru/api/common/v1/payment_commission?origin=web%2Cib5%2Cplatform'

    depends_on:
      - db
    ports:
      - 7000:7000
